name: Edit Job
description: Edit a job on our list
title: "Editing Job"
labels: ["edit_job"]
body:
  - type: markdown
    attributes:
      value: |
        ## Formulario para editar un trabajo
        ¡Gracias por tomarte el tiempo de ayudarnos!
        > Asegúrate de hacer leído el `CONTRIBUTING.md` antes de enviar tus cambios
        Por favor únicamente llena **link, razón y cualquier otro campo que quieras cambiar**
        Puedes dejar los demás vacíos
  - type: input
    id: url
    attributes:
      label: Link a la publicación del trabajo
      placeholder: ex. example.com/link/to/posting
    validations:
      required: true
  - type: input
    id: company_name
    attributes:
      label: Nombre de la compañía
      placeholder: ex. Google
    validations:
      required: false
  - type: input
    id: title
    attributes:
      label: Título del trabajo
      placeholder: ex. ML Software Engineer
    validations:
      required: false
  - type: input
    id: location
    attributes:
      label: Lugar
      description: |
        ¿Dónde está ubicado?
        Por favor separa los lugares con un *pipe* "|" si son varios lugares.
        Incluye *Remoto* si la opción de hacerlo remoto está disponible.
      placeholder: ex. Ciudad de México, México | Tlaquepaque, Jalisco | Remoto
    validations:
      required: false
  - type: dropdown
    id: level
    attributes:
      label: ¿Para qué nivel es el trabajo?
      description: |
        ¿Qué tipo de posición es?
        Un Semi Sr (al menos 2 años de experiencia) es por ejemplo un SWE II, 
        un Sr+ (al menos 5 años de experiencia) es desde Sr hasta Staff, Principal, etc.
      multiple: true
      options:
        - New Grad
        - Semi Sr
        - Sr+
    validations:
      required: false
  - type: dropdown
    id: english
    attributes:
      label: ¿La posición necesita saber inglés?
      description: |
        Si la publicación no lo especifica, selecciona "Dunno" (aka "don't know")
      multiple: false
      options:
        - "Yes"
        - "No"
        - "Dunno"
    validations:
      required: false
  - type: dropdown
    id: active
    attributes:
      label: ¿El trabajo está recibiendo aplicaciones actualmente?
      multiple: false
      options:
        - "Yes"
        - "No"
    validations:
      required: false
  - type: checkboxes
    id: is_visible
    attributes:
      label: ¿Eliminar este trabajo de la lista?
      description: Sólo selecciona esta casilla si el trabajo es *fake* (falso), no encaja con la temática del repositorio (ej. es de diseñador) o es ofensivo.
      options:
        - label: "Sí, eliminar este trabajo"
  - type: input
    id: email
    attributes:
      label: Email asociado a tu cuenta de GitHub (opcional)
      description: |
        Si quieres ser añadido como **Contributor** en el repositorio cuando el *github action* añada
        tu contribución al repositorio, por favor añade tu email. Sólo usaremos tu email para esto. Si 
        lo dejas en blanco, tu contribución será hecha de forma anónima por el bot actions@github.com.
      placeholder: ex. firstLast@gmail.com
    validations:
      required: false
  - type: textarea
    id: reason
    attributes:
      label: Razón para editar
      description: Si el motivo de tu edición no es obvio (e incluso si lo es), por favor explícala aquí.
      placeholder: This Job is no longer accepting applications...
    validations:
      required: false
      
